### ISSUE TITLE
Closed in WordPress.org plugin directory?

### ISSUE THREAD

**Issue by alvarogois** [brainstormforce/cf7-to-google-sheet-extension#12]
Hi,

I was looking for this plugin in WordPress.org plugin directory and realised that it's been [closed](https://pt.wordpress.org/plugins/cf7-to-google-sheet-extension/) as of April 2nd 2020. Are there any security issues with it? Is it being discontinued?

Thanks.

Álvaro

**Comment by sujaypawar** [comment]
Hi Álvaro, thanks for writing in. As we decided to discontinue the plugin, we removed it from the repository. There were no security issues.

The decision to discontinue the plugin was mainly due to the fact that there are better alternatives available which are actively supported and maintained.

**Comment by alvarogois** [comment]
Thank you @sujaypawar. What would you suggest as a better alternative, judging by your experience?
